name: ReaPack Index

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate ReaPack Index
        uses: cfillion/reapack-index-action@v1
        with:
          auto-commit: true
